version: '2'
services:
    spinserver-app:
        image: spinserver
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://spinserver-mysql:3306/spinserver?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    spinserver-mysql:
        extends:
            file: mysql.yml
            service: spinserver-mysql
